// tags and attribute lists are from HTMLParser
// https://git.soma.salesforce.com/forcedotcommons/commons-text/blob/master/src/main/java/com/force/commons/htmlparser/HTMLParserBase.java
// Please keep in sync with secure-ui-output-rich-text-rule.js

const tagsWhitelist = Object.freeze([
    //TEXT_ELEMENTS
    'abbr',
    'acronym',
    'address',
    'blockquote',
    'br',
    'cite',
    'code',
    'dfn',
    'div',
    'em',
    'font',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'kbd',
    'p',
    'pre',
    'q',
    'samp',
    'span',
    'strong',
    'u',
    'var',
    'strike',

    //HYPERTEXT_ELEMENTS
    'a',

    //LIST_ELEMENTS
    'dl',
    'dt',
    'dd',
    'ol',
    'ul',
    'li',

    //PRESENTATION_ELEMENTS
    'b',
    'big',
    'hr',
    'i',
    'small',
    'sub',
    'sup',
    'tt',

    //EDIT_ELEMENTS
    'del',
    'ins',

    //BIDIRECTIONAL_ELEMENTS
    'bdo',

    //TABLE_ELEMENTS
    'caption',
    'col',
    'colgroup',
    'table',
    'tbody',
    'td',
    'tfoot',
    'th',
    'thead',
    'tr',

    //IMAGE_ELEMENTS
    'img',

    //DEPRECATED_TEXT_ELEMENTS
    'center',
    'xmp',
    's',
    'dir',
    'menu',
    'basefont',

    //INPUT_ELEMENTS
    'form',
    'input',
    'textarea',
    'button',
    'select',
    'optgroup',
    'option',
    'label',
    'fieldset',
    'legend',

    //MAP_ELEMENTS
    'map',
    'area',

    //VIDEO_ELEMENTS
    'iframe'
]);

const attrWhitelist = Object.freeze([
    //BASIC_ATTRIBUTES
    'align',
    'alt',
    'href',
    'src',
    'size',
    'face',
    'style',
    'border',
    'background',
    'width',
    'height',
    'rowspan',
    'colspan',
    'color',
    'class',
    'start',
    'title',
    'valign',

    //TABLE_ATTRIBUTES
    'cellspacing',
    'cellpadding',
    'summary',

    //ADDITIONAL_ATTRIBUTES
    'abbr',
    'accept-charset',
    'accept',
    'accesskey',
    'action',
    'alink',
    'autocomplete',
    'axis',
    'bgcolor',
    'char',
    'charoff',
    'charset',
    'checked',
    'cite',
    'classid',
    'clear',
    'code',
    'codebase',
    'codetype',
    'cols',
    'compact',
    'content',
    'coords',
    'data',
    'datetime',
    'declare',
    'default',
    'defer',
    'dir',
    'disabled',
    'download',
    'enctype',
    'for',
    'headers',
    'hreflang',
    'hspace',
    'http-equiv',
    'id',
    'ismap',
    'label',
    'lang',
    'language',
    'link',
    'list',
    'longdesc',
    'loop',
    'low',
    'marginheight',
    'marginwidth',
    'max',
    'maxlength',
    'media',
    'method',
    'min',
    'multiple',
    'name',
    'nohref',
    'noresize',
    'noshade',
    'novalidate',
    'nowrap',
    'open',
    'optimum',
    'pattern',
    'placeholder',
    'poster',
    'preload',
    'pubdate',
    'radiogroup',
    'readonly',
    'rel',
    'required',
    'rev',
    'reversed',
    'rows',
    'rules',
    'scheme',
    'scope',
    'scrolling',
    'selected',
    'shape',
    'span',
    'spellcheck',
    'srclang',
    'standby',
    'step',
    'tabindex',
    'target',
    'text',
    'type',
    'usemap',
    'value',
    'valuetype',
    'version',
    'vlink',
    'vspace',
    'xmlns',

    //VIDEO_ATTRIBUTES
    'frameborder',
    'allowfullscreen',
    'mozallowfullscreen',
    'webkitallowfullscreen'
]);

export const richTextConfig = Object.freeze({
    ALLOWED_TAGS: tagsWhitelist,
    ALLOWED_ATTR: attrWhitelist,
    ALLOW_UNKNOWN_PROTOCOLS: false
});
